### ISSUE TITLE
1.20.1 & 1.20 portback

### ISSUE THREAD

**Issue by MarkinhosMLP** [trainb0y/FabriZoom#16]
please

**Comment by trainb0y** [comment]
For the most part, I really don't want to support old Minecraft versions. If someone else wants to maintain them, that's fine, but it's a lot of extra work for me.

I'm currently working on a major rework of the mod (to support Forge and NeoForge alongside Fabric) and the current code is a lot different than the 1.20 version (mojang mappings, different config handling, rewritten gradle nonsense), and backporting all of that would be a pain.

*However*, before 1.20.2 came out I did update the mod to 1.20 (just never released it) and I guess I might as well put that version on Modrinth. It won't have any of the more recent features, and those versions **won't get any further updates or fixes**, but otherwise it should work.

I'll link it here when it's uploaded.

**Comment by trainb0y** [comment]
Backported [1.3.0](https://github.com/trainb0y/FabriZoom/releases/tag/1.3.0) to 1.20.1 (should also work on 1.20) with https://github.com/trainb0y/FabriZoom/commit/1621df665a081b91df3e858026512d21a036a46b Didn't end up using that old version, backporting 1.3 was easier. I didn't test it that thoroughly, but I don't think anything is broken.

The versioning scheme for this is garbage, with 2.0 (coming soon) the mod version will include the target Minecraft version.

https://modrinth.com/mod/fabrizoom/version/cXNh4ggJ
