### ISSUE TITLE
Backport to 1.18.2

### ISSUE THREAD

**Issue by heldheld** [trainb0y/FabriZoom#9]
Since some older versions of Ok Zoomer are now no longer working, with no hopes of that being resolved, is there any way that you could backport FabriZoom to 1.18.2?

**Comment by trainb0y** [comment]
The mod uses [YetAnotherConfigLib](https://github.com/isXander/YetAnotherConfigLib) for the configuration screen, which doesn't exist for any version older than 1.19.2.

It used to use SpruceUI, which does have older versions, so that version could probably be backported to 1.18, but I don't really want to try to support two versions of the code that are so drastically different, especially since the SpruceUI GUI was a buggy mess.

I am curious though, why would OkZoomer stop working for 1.18.2?

**Comment by heldheld** [comment]
I'm not sure, something with the fabric loader changing something? EnnuiLangeweile has written about it on the curseforge page https://www.curseforge.com/minecraft/mc-mods/ok-zoomer at _'Why is 5.0.0-beta.6 (the last Fabric version) not working on Fabric???'_ and the corresponding spoiler.

I managed to be able to load up single player worlds on 1.18.2 with these versions of Ok Zoomer, and only these:
-okzoomer-5.0.0-beta.2+1.17
-okzoomer-5.0.0-beta.3+1.17.1
And with ALL of them, the game crashed when I try to enter any multiplayer server.

**Comment by trainb0y** [comment]
Huh, I didn't realize OkZoomer was using QSL on Fabric, but I'm not surprised that that eventually broke.

If you want to send a crash log I can take a look, not sure there's much that can be done though.

**Comment by trainb0y** [comment]
https://github.com/EnnuiL/OkZoomer/commit/9dde440ae4f64e6c549c45970bc4e8e597e31d83 I think this is probably the last commit that will work on Fabric. 

Unless Quilt breaks a mod you use, it might be easier to just switch to Quilt.

**Comment by heldheld** [comment]
> If you want to send a crash log I can take a look, not sure there's much that can be done though.
[crash-2022-12-15_14.14.36-client.txt](https://github.com/trainb0y/FabriZoom/files/10237238/crash-2022-12-15_14.14.36-client.txt)
This is the crash report I get when I try to connect to Hypixel. I know there are quite a few other mods in there too, but it's only when I add Ok Zoomer that it crashes.

> [EnnuiL/OkZoomer@9dde440](https://github.com/EnnuiL/OkZoomer/commit/9dde440ae4f64e6c549c45970bc4e8e597e31d83) I think this is probably the last commit that will work on Fabric.
That is for 1.19 if I'm not mistaken, got no issues with that since I can use FabriZoom :)

> Unless Quilt breaks a mod you use, it might be easier to just switch to Quilt.
Unfortunately it does, otherwise I would have done so!

**Comment by trainb0y** [comment]
> [crash-2022-12-15_14.14.36-client.txt](https://github.com/trainb0y/FabriZoom/files/10237238/crash-2022-12-15_14.14.36-client.txt) This is the crash report I get when I try to connect to Hypixel. I know there are quite a few other mods in there too, but it's only when I add Ok Zoomer that it crashes.

Huh weird. I have no idea what would cause this. As far as I can tell (from looking at yarn mappings) that crash has to do with identifier tags, and OkZoomer wouldn't be touching any of that. Its probably a QSL on Fabric thing, and I doubt there's much that can be done about it.

I did some digging around the Fabric discord server:
![image](https://user-images.githubusercontent.com/66213737/207975456-8f68de16-a237-4973-bbfe-4ec48660d0d1.png)

There's also a very similar crash here:
https://discord.com/channels/507304429255393322/507982463449169932/982418909116375050 
![image](https://user-images.githubusercontent.com/66213737/207975686-752ce36c-a1c5-4e6c-8a50-ab2d08be8d27.png)

Which would make sense considering 
> I managed to be able to load up single player worlds on 1.18.2 with these versions of Ok Zoomer, and only these:
-okzoomer-5.0.0-beta.2+1.17
-okzoomer-5.0.0-beta.3+1.17.1

When 1.18.2 came out I compiled myself a custom build of okzoomer. I haven't used it in months, and I'm not sure if it broke with fabric loader 0.14, but [here it is](https://drive.google.com/file/d/17xL3fV1EHhUHi7hfa3XZz0P9fI51nrwG/view?usp=sharing) if you want to try it.

Otherwise I'm not sure there's much that can be done, you might want to try WI Zoom or Logical Zoom.
[Zoomify 1.18](https://github.com/isXander/Zoomify/tree/1.18) is another good option and probably has the most features.

**Comment by heldheld** [comment]
> When 1.18.2 came out I compiled myself a custom build of okzoomer. I haven't used it in months, and I'm not sure if it broke with fabric loader 0.14, but [here it is](https://drive.google.com/file/d/17xL3fV1EHhUHi7hfa3XZz0P9fI51nrwG/view?usp=sharing) if you want to try it.

This one actually works perfectly!! This is so great, thanks so much for sharing it and explaining what you came across! I really appreciate you taking the time :)
